FROM python:3.11-slim

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install mlflow==2.14.1

RUN mkdir -p /app/mlruns

EXPOSE 8080

CMD ["mlflow", "ui", "--backend-store-uri", "/app/mlruns", "--host", "0.0.0.0", "--port", "8080"]
